
#pragma once

#include "clipp/clipp.hpp"

namespace pride::cli
{
    using pride::cli::clipp::any;
    using pride::cli::clipp::any_other;
    using pride::cli::clipp::arg_index;
    using pride::cli::clipp::arg_list;
    using pride::cli::clipp::arg_string;
    using pride::cli::clipp::command;
    using pride::cli::clipp::decrement;
    using pride::cli::clipp::doc_formatting;
    using pride::cli::clipp::doc_string;
    using pride::cli::clipp::documentation;
    using pride::cli::clipp::flip;
    using pride::cli::clipp::for_all_params;
    using pride::cli::clipp::greedy;
    using pride::cli::clipp::group;
    using pride::cli::clipp::in_sequence;
    using pride::cli::clipp::increment;
    using pride::cli::clipp::integer;
    using pride::cli::clipp::integers;
    using pride::cli::clipp::joinable;
    using pride::cli::clipp::make_man_page;
    using pride::cli::clipp::man_page;
    using pride::cli::clipp::match_function;
    using pride::cli::clipp::match_predicate;
    using pride::cli::clipp::number;
    using pride::cli::clipp::numbers;
    using pride::cli::clipp::one_of;
    using pride::cli::clipp::opt_integer;
    using pride::cli::clipp::opt_integers;
    using pride::cli::clipp::opt_number;
    using pride::cli::clipp::opt_numbers;
    using pride::cli::clipp::opt_value;
    using pride::cli::clipp::opt_values;
    using pride::cli::clipp::opt_word;
    using pride::cli::clipp::opt_words;
    using pride::cli::clipp::option;
    using pride::cli::clipp::param_filter;
    using pride::cli::clipp::parameter;
    using pride::cli::clipp::parse;
    using pride::cli::clipp::parser;
    using pride::cli::clipp::parsing_result;
    using pride::cli::clipp::pattern;
    using pride::cli::clipp::repeatable;
    using pride::cli::clipp::required;
    using pride::cli::clipp::set;
    using pride::cli::clipp::subrange;
    using pride::cli::clipp::tri;
    using pride::cli::clipp::unset;
    using pride::cli::clipp::usage_lines;
    using pride::cli::clipp::value;
    using pride::cli::clipp::values;
    using pride::cli::clipp::with_prefix;
    using pride::cli::clipp::with_prefixes_short_long;
    using pride::cli::clipp::word;
    using pride::cli::clipp::words;
}
